### ISSUE TITLE
[BUG] Newlines are ignored in card's Chat Message

### ISSUE THREAD

**Issue by Rayji96** [EvaTheDM/mildly-magical-inspiration#12]
**Describe the bug**
When using a card, newlines in the card description aren't rendered in the chat message.

**To Reproduce**
1. Create a card with newlines in its description
2. Assign the card to a player
3. Use the card
4. See that the newlines are ignored in the Chat Message

**Expected behavior**
Newlines are not ignored and are outputted as they are formatted in the description when creating the card.

**Screenshots**
![image](https://user-images.githubusercontent.com/9367653/108624225-7495f380-73f8-11eb-8625-9071a108800b.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Foundry Version: 0.7.9
 - Module Version: 1.0.1

**Additional context**
Foundry doesn't escape html in text messages. {{editor}}, a Handlebars helper built into Foundry can save text with html formatting to a card attribute.

**Comment by EvaTheDM** [comment]
Thanks! Will make sure to fix that.

**Comment by EvaTheDM** [comment]
fixed with v2.0.0
