### ISSUE TITLE
[FEATURE] Show Card Description in Hand

### ISSUE THREAD

**Issue by Rayji96** [EvaTheDM/mildly-magical-inspiration#13]
**Is your feature request related to a problem? Please describe.**
When giving cards to players, there is no way to see the description of a card until you use the card.

**Describe the solution you'd like**
An option to show card description with title and subtitle when viewing cards in hand.

**Describe alternatives you've considered**
Using the card to see the description without discarding the card.

**Additional context**
I'm currently using Mildly Magical Inspiration for Twitch the Fiend Inspiration Cards. My current workaround is to put the actual card description in the subtitle instead of the description.

**Comment by EvaTheDM** [comment]
Thanks! I somehow missed this in the original release. Will make sure to add it.

**Comment by EvaTheDM** [comment]
fixed/added with v2.0.0
