### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by HippyCraig** [EvaTheDM/mildly-magical-inspiration#15]
A sample file would be helpful  I dont know how to really set this up.  Maybe a video or something to show its usage would be good as well.

**Comment by EvaTheDM** [comment]
added with v.2.0.0
There is currently no video but an in-depth explanation of how to set the deck up and basic usage in the [wiki](https://github.com/EvaTheDM/mildly-magical-inspiration/wiki/Getting-Started)
A sample file can also be found in the [wiki](https://github.com/EvaTheDM/mildly-magical-inspiration/wiki/Available-Sources).
