### ISSUE TITLE
[BUG] Giving choices to multiple players breaks the module

### ISSUE THREAD

**Issue by FI-Aquacrest** [EvaTheDM/mildly-magical-inspiration#19]
**Describe the bug**
Awarding a choice for an inspiration card for multiple players seems to break the system.

**To Reproduce**
1. Be in a session as GM with at least 2 online players
2. Set the "random size" -setting to >1
2. Award a card to a player
3. Award a card to another player while the previous player has not yet made their choice
4. Second player will not see a choice but they still count as having a card
5. If a player with an "invisible" (step 4) card tries to use one, the "used" notification will loop forever

**Expected behavior**
Multiple people should be able to choose their cards simultaneously OR the GM should be blocked from giving new cards before a decision is made. As a side issue, recalling the cards does not close the card choice dialogue, meaning a player can choose and receive a card even though the cards have been recalled.

**Desktop:**
 - OS: Windows 10 Pro
 - Foundry Version 0.7.9
 - Module Version 2.0.0

**Additional context**
I am using other modules and have not yet had the chance to try this module on its own, but this feels like an issue with the mod rather than a conflict.

**Comment by EvaTheDM** [comment]
Thank you for the indepth description on how to repoduce the error.
I have found what has been causing it and an [update](https://github.com/EvaTheDM/mildly-magical-inspiration/releases/tag/v2.0.1) has been released!
