### ISSUE TITLE
Can't find award cards. :)

### ISSUE THREAD

**Issue by RavenknightDM** [EvaTheDM/mildly-magical-inspiration#2]
Hiya, this module looks awesome! In fact I've been looking for something like this since we switched to Foundry. (Dramacards! Woo!) But I'm at a loss how I award cards to my players. Where is the button?

(Are you active on Discord by any chance? I couldn't find a @EvaTheDM in the memberlist.)

**Comment by RavenknightDM** [comment]
Reloaded the deck and now it works. Must have been a hiccup in my installation. :) Now to create an awesome deck. Thanks.

**Comment by EvaTheDM** [comment]
Hey, thanks for the info! That’s probably a bug I’ll have to fix with a forced reload after the setup finishes. Hope you’ll enjoy the module!
